# Azure Files storage using AKS Managed Identity
# The CSI driver uses managed identity to automatically retrieve storage account keys
# No secrets required - AKS kubelet identity has Storage Account Contributor role
apiVersion: v1
kind: PersistentVolume
metadata:
  name: docling-models-pv
  labels:
    usage: docling-models
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: docling-models-unique-${STORAGE_ACCOUNT_NAME}
    volumeAttributes:
      storageAccount: ${STORAGE_ACCOUNT_NAME}
      shareName: models
      # Specify the resource group where the storage account is located
      resourceGroup: ${AZURE_RESOURCE_GROUP}
      # CSI driver will use AKS managed identity to retrieve storage key automatically
      getLatestAccountKey: "true"
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - actimeo=30
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docling-models-pvc
  namespace: docling
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: docling-models-pv
  resources:
    requests:
      storage: 50Gi
